### ISSUE TITLE
line 180

### ISSUE THREAD

**Issue by cpcpcp11** [beaston02/CamsodaRecorder#13]
checking for online models
Traceback (most recent call last):
  File "C:\Users\User\Desktop\CamsodaRecorder\main.py", line 23, in <module>
    if should_record_model(conf.settings).check(model):
  File "C:\Users\User\Desktop\CamsodaRecorder\classes\camsoda.py", line 180, in check
    if model['username'] in Wanted(self._settings).wanted_models:
KeyError: 'username'

hopefully someone can help with this!.....started happening like a week or 2 ago.  Thanks.

**Comment by fnzeta** [comment]
@cpcpcp11 i have updated the code, it working currently you can find it here
[https://github.com/fnzeta/Camsoda-Recorder](https://github.com/fnzeta/Camsoda-Recorder)
