### ISSUE TITLE
seems like getting error on status when connecting to Camsoda

### ISSUE THREAD

**Issue by tsauce** [beaston02/CamsodaRecorder#4]
Started happening about 2 weeks ago ? Just didn't have time post earlier.
Any suggestions? 

side$ CamsodaRecorder (master) $ python3.5 CamsodaRecorder.py
Traceback (most recent call last):
  File "CamsodaRecorder.py", line 80, in <module>
    getOnlineModels()
  File "CamsodaRecorder.py", line 29, in getOnlineModels
    if line['username'].lower() not in recording and line['status'] != 'connected':
KeyError: 'status'

**Comment by ghost** [comment]
I don't know but I am getting the same error.
Glad it is not just my comptuer

**Comment by longsack** [comment]
Same error here..... I think Beaston02 is busy, i'm looking at seeing if I can find a programmer to fix this issue.  I looked at it but I have no idea what i'm looking at.  will post an update if I get a solution.

**Comment by nickartis** [comment]
i got the error to leave and it detects the model at the start of the countdown, but it doesnt anything nor does it detect the model after 1 second. This is the change i made, "if line['username'].lower() not in recording and **line.get('status')** != 'connected':".

**Comment by nickartis** [comment]
Did a lil debugging and I think the issue is related to the streams url

**Comment by asap1en** [comment]
So as far as i can tell there are a couple errors, one is that they seem to leave off status: connected if its connected, and the other is that the stream url isnt being created properly.
I changed line 30 to ;
           ` if line['username'].lower() not in recording and  line.get('status') != 'connected':`
as nickartis suggested
and line 48 to
        `    elif modelData['status'] == 'online' or not hasattr(modelData,'status'):`
rather than checking if it has status; connected it checks if status doesn't exist.

so line 41 doesn't seem to being retaining the online models name but I think its related to the next error.

and then 42- 43 is the big error
```
 videoapi = requests.get(
                "https://www.camsoda.com/api/v1/video/vtoken/{model}?username=guest_{num}".format(model=modelData['username'], num=num), headers=headers)
```
is returning "response[200]" instead of what i think should be server urls.   Even figureing out this much is stretching my debugging skills (actually learned out to sort of use liclipse for it).  If someone can figure out the requests line, I think everything would work.

**Comment by ls117** [comment]
and what drives it home is there are people who know this information. not saying they're wrong for keeping it to themselves, but at the same time i'd like to keep what i pay for.  i would never pay for a ticket show if i couldnt save it.
